cloud_provider = ""

pm_api_url = ""
pm_password = ""
api_token  = ""
private_key = ""

vm_name            = ""
vm_username        = ""
vm_password        = ""
target_node        = ""
template_id        = ""
vm_memory          = ""
vm_cores           = ""
vm_disk_size       = ""
tailscale_auth_key = ""
k3s_url            = ""
k3s_token          = ""
